// Barrel de compatibilidade - redireciona para nova localização
export * from '@/shared/ui/ELButton';
export * from '@/shared/ui/ELInput';
export * from '@/shared/ui/ELSelect';
export * from '@/shared/ui/ELCard';
export * from '@/shared/ui/ELModal';
export * from '@/shared/ui/ELDrawer';
export * from '@/shared/ui/ELAlert';
export * from '@/shared/ui/ELEmpty';
export * from '@/shared/ui/ELTag';
export * from '@/shared/ui/ELStatusTag';
export * from '@/shared/ui/ELFormItem';
export * from '@/shared/ui/ELSkeleton';
export * from '@/shared/ui/ELGrid';
export * from '@/shared/ui/ELTableToolbar';
export * from '@/shared/ui/ActionBar';
export * from '@/shared/ui/AppContainer';
export * from '@/shared/ui/DataTable';
export * from '@/shared/ui/FormCard';
export { QuoteResultCard } from '@/modules/quotes/ui/components/QuoteResultCard';
export { QuoteSummary } from '@/modules/quotes/ui/components/QuoteSummary';
export { ShipmentsTable } from '@/modules/shipments/ui/components/shipments-table';
export { ShipmentStatusBadge } from '@/modules/shipments/ui/components/shipment-status-badge';
export { TrackingTimeline } from '@/modules/tracking/ui/components/TrackingTimeline';
export { TrackingStatusTag } from '@/modules/tracking/ui/components/TrackingStatusTag';
export { PickupTimeline } from '@/modules/pickup-points/ui/components/PickupTimeline';
export { PickupStatusTag } from '@/modules/pickup-points/ui/components/PickupStatusTag';
